trigger:
- main


pool: MK-agent

stages:
- stage: buildinitinstallplan
  displayName: terraform install, init and plan

  jobs:
  - job: Terraforminstallinit
    displayName: Terraform Install,Init and plan
    steps:
        
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: -reconfigure
        workingDirectory: '$(System.DefaultWorkingDirectory)/MapProject'
        backendServiceArm: 'mkscon'
        backendAzureRmResourceGroupName: 'rashi'
        backendAzureRmStorageAccountName: 'rashistrg'
        backendAzureRmContainerName: 'rashicont'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/MapProject'
        environmentServiceNameAzureRM: 'mkscon'
    
    
- stage: scanning
  displayName: Terraform scanning

  jobs:
  - job: Terraforrscanning
    displayName: Terraform scanning
    pool: MK-agent
  

    steps:

    - task: PowerShell@2
      displayName: Install and Run tfsec
      inputs:
       targetType: 'inline'
       script: |
        Write-Host "Installing tfsec..."
        Invoke-WebRequest -Uri "https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-windows-amd64.exe" -OutFile "tfsec.exe"
        Write-Host "Running tfsec..." ./tfsec.exe ./MapProject
      


- stage: validateandapply
  displayName: Terraform validate and Apply
  dependsOn: buildinitinstallplan

  jobs:
  - job: Terrraformmanualvalidation
    displayName: Manual Validation
    pool: server
    steps:
    
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'mkaz20252025@outlook.com'
        approvers: 'mkaz20252025@outlook.com'

  
  - job: Terrraforminitapply
    dependsOn: Terrraformmanualvalidation
    displayName: Terraform Init and Apply

    steps:
        
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: -reconfigure
        workingDirectory: '$(System.DefaultWorkingDirectory)/MapProject'
        backendServiceArm: 'mkscon'
        backendAzureRmResourceGroupName: 'rashi'
        backendAzureRmStorageAccountName: 'rashistrg'
        backendAzureRmContainerName: 'rashicont'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/MapProject'
        environmentServiceNameAzureRM: 'mkscon'

  
  