trigger: none

pool: MK-agent

stages:
- stage: buildinitinstallplan
  displayName: terraform install, init and plan

  jobs:
  - job: Terraforminstallinit
    displayName: Terraform Install,Init and plan
    steps:
        
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/MapProject'
        backendServiceArm: 'mkscon'
        backendAzureRmResourceGroupName: 'rashi'
        backendAzureRmStorageAccountName: 'rashistrg'
        backendAzureRmContainerName: 'rashicont'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/MapProject'
        environmentServiceNameAzureRM: 'mkscon'
    
    
- stage: scanning
  displayName: Terraform scanning

  jobs:
  - job: Terraforrscanning
    displayName: Terraform scanning
    pool: MK-agent
  

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        echo "Installing tfsec..."
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      displayName: Install tfsec

    - script: |
       echo "Running tfsec scan (non-blocking)..."
       tfsec $(System.DefaultWorkingDirectory)/MapProject || echo "tfsec found issues, but continuing."
      displayName: Run tfsec (non-blocking)
 
    


- stage: validateandapply
  displayName: Terraform validate and Apply
  dependsOn: buildinitinstallplan

  jobs:
  - job: Terrraformmanualvalidation
    displayName: Manual Validation
    pool: server
    steps:
    
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'mkaz20252025@outlook.com'
        approvers: 'mkaz20252025@outlook.com'

  
  - job: Terrraforminitapply
    dependsOn: Terrraformmanualvalidation
    displayName: Terraform Init and Apply

    steps:
        
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/MapProject'
        backendServiceArm: 'mkscon'
        backendAzureRmResourceGroupName: 'rashi'
        backendAzureRmStorageAccountName: 'rashistrg'
        backendAzureRmContainerName: 'rashicont'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/MapProject'
        environmentServiceNameAzureRM: 'mkscon'

  
  